name: Compile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci and compile
        run: |
          npm ci
          npm run compile
          cd client
          npm run lint
          npm test
        env:
          CI: true
